.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. xero_qt test_xero_qt
clean: FORCE
	$(MAKE) -C .. xero_qt_clean test_xero_qt_clean
check: FORCE
	$(MAKE) -C .. test_xero_qt_check
xero-qt xero-qt.exe: FORCE
	 $(MAKE) -C .. xero_qt
apk: FORCE
	$(MAKE) -C .. xero_qt_apk
